// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: guardians.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGuardian = `-- name: DeleteGuardian :exec
DELETE FROM guardians WHERE guardian_id = $1
`

func (q *Queries) DeleteGuardian(ctx context.Context, guardianID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGuardian, guardianID)
	return err
}

const getAllStudentGuardianLinks = `-- name: GetAllStudentGuardianLinks :many
SELECT
    g.guardian_id,
    s.last_name AS student_first_name,
    s.first_name AS student_last_name,
    g.guardian_name AS guardian_name,
    g.phone_number_1,
    g.phone_number_2,
    g.gender AS guardian_gender,
    g.profession AS guardian_profession
FROM students s
INNER JOIN student_guardians sg ON s.student_id = sg.student_id
INNER JOIN guardians g ON sg.guardian_id = g.guardian_id
ORDER BY s.last_name, s.first_name
`

type GetAllStudentGuardianLinksRow struct {
	GuardianID         uuid.UUID   `json:"guardian_id"`
	StudentFirstName   string      `json:"student_first_name"`
	StudentLastName    string      `json:"student_last_name"`
	GuardianName       string      `json:"guardian_name"`
	PhoneNumber1       pgtype.Text `json:"phone_number_1"`
	PhoneNumber2       pgtype.Text `json:"phone_number_2"`
	GuardianGender     string      `json:"guardian_gender"`
	GuardianProfession pgtype.Text `json:"guardian_profession"`
}

func (q *Queries) GetAllStudentGuardianLinks(ctx context.Context) ([]GetAllStudentGuardianLinksRow, error) {
	rows, err := q.db.Query(ctx, getAllStudentGuardianLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllStudentGuardianLinksRow{}
	for rows.Next() {
		var i GetAllStudentGuardianLinksRow
		if err := rows.Scan(
			&i.GuardianID,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.GuardianName,
			&i.PhoneNumber1,
			&i.PhoneNumber2,
			&i.GuardianGender,
			&i.GuardianProfession,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuardianByID = `-- name: GetGuardianByID :one
SELECT guardian_id, guardian_name, phone_number_1, phone_number_2, gender, profession from guardians WHERE guardian_id = $1
`

func (q *Queries) GetGuardianByID(ctx context.Context, guardianID uuid.UUID) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardianByID, guardianID)
	var i Guardian
	err := row.Scan(
		&i.GuardianID,
		&i.GuardianName,
		&i.PhoneNumber1,
		&i.PhoneNumber2,
		&i.Gender,
		&i.Profession,
	)
	return i, err
}

const getGuardianByPhone = `-- name: GetGuardianByPhone :one
SELECT guardian_id, guardian_name, phone_number_1, phone_number_2, gender, profession FROM guardians
WHERE phone_number_1 = $1
OR phone_number_2 = $1
`

func (q *Queries) GetGuardianByPhone(ctx context.Context, phoneNumber1 pgtype.Text) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardianByPhone, phoneNumber1)
	var i Guardian
	err := row.Scan(
		&i.GuardianID,
		&i.GuardianName,
		&i.PhoneNumber1,
		&i.PhoneNumber2,
		&i.Gender,
		&i.Profession,
	)
	return i, err
}

const getStudentGuardianCount = `-- name: GetStudentGuardianCount :one
WITH student_guardian AS (
    SELECT guardian_id FROM student_guardians
    WHERE  student_guardians.student_id = $1
)
SELECT COUNT(guardian_id), guardian_id FROM student_guardians   WHERE guardian_id = (SELECT student_guardian.guardian_id FROM student_guardian)
GROUP BY student_guardians.guardian_id
`

type GetStudentGuardianCountRow struct {
	Count      int64     `json:"count"`
	GuardianID uuid.UUID `json:"guardian_id"`
}

func (q *Queries) GetStudentGuardianCount(ctx context.Context, studentID uuid.UUID) (GetStudentGuardianCountRow, error) {
	row := q.db.QueryRow(ctx, getStudentGuardianCount, studentID)
	var i GetStudentGuardianCountRow
	err := row.Scan(&i.Count, &i.GuardianID)
	return i, err
}

const searchStudentGuardian = `-- name: SearchStudentGuardian :many
SELECT
    g.guardian_id,
    s.first_name AS student_first_name,
    s.last_name AS student_last_name,
    g.guardian_name AS guardian_name,
    g.phone_number_1,
    g.phone_number_2,
    g.gender AS guardian_gender,
    g.profession AS guardian_profession
FROM students s
INNER JOIN student_guardians sg ON s.student_id = sg.student_id
INNER JOIN guardians g ON sg.guardian_id = g.guardian_id
WHERE s.first_name ILIKE $1 OR s.last_name ILIKE $1
ORDER BY s.last_name, s.first_name
`

type SearchStudentGuardianRow struct {
	GuardianID         uuid.UUID   `json:"guardian_id"`
	StudentFirstName   string      `json:"student_first_name"`
	StudentLastName    string      `json:"student_last_name"`
	GuardianName       string      `json:"guardian_name"`
	PhoneNumber1       pgtype.Text `json:"phone_number_1"`
	PhoneNumber2       pgtype.Text `json:"phone_number_2"`
	GuardianGender     string      `json:"guardian_gender"`
	GuardianProfession pgtype.Text `json:"guardian_profession"`
}

func (q *Queries) SearchStudentGuardian(ctx context.Context, firstName string) ([]SearchStudentGuardianRow, error) {
	rows, err := q.db.Query(ctx, searchStudentGuardian, firstName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchStudentGuardianRow{}
	for rows.Next() {
		var i SearchStudentGuardianRow
		if err := rows.Scan(
			&i.GuardianID,
			&i.StudentFirstName,
			&i.StudentLastName,
			&i.GuardianName,
			&i.PhoneNumber1,
			&i.PhoneNumber2,
			&i.GuardianGender,
			&i.GuardianProfession,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGuardian = `-- name: UpdateGuardian :exec
UPDATE guardians
SET guardian_name = COALESCE($2, guardian_name),
    phone_number_1 = COALESCE($3, phone_number_1),
    phone_number_2 = COALESCE($4, phone_number_2),
    gender = COALESCE($5, gender),
    profession = COALESCE($6, profession)
WHERE guardian_id = $1
`

type UpdateGuardianParams struct {
	GuardianID   uuid.UUID   `json:"guardian_id"`
	GuardianName string      `json:"guardian_name"`
	PhoneNumber1 pgtype.Text `json:"phone_number_1"`
	PhoneNumber2 pgtype.Text `json:"phone_number_2"`
	Gender       string      `json:"gender"`
	Profession   pgtype.Text `json:"profession"`
}

func (q *Queries) UpdateGuardian(ctx context.Context, arg UpdateGuardianParams) error {
	_, err := q.db.Exec(ctx, updateGuardian,
		arg.GuardianID,
		arg.GuardianName,
		arg.PhoneNumber1,
		arg.PhoneNumber2,
		arg.Gender,
		arg.Profession,
	)
	return err
}
