// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	dto "school_management_system/internal/dto"
)

type AcademicYear struct {
	AcademicYearID  uuid.UUID                 `json:"academic_year_id"`
	GraduateClassID pgtype.UUID               `json:"graduate_class_id"`
	Name            string                    `json:"name"`
	StartDate       pgtype.Date               `json:"start_date"`
	EndDate         pgtype.Date               `json:"end_date"`
	Active          bool                      `json:"active"`
	Period          pgtype.Range[pgtype.Date] `json:"period"`
}

type Assignment struct {
	ID        uuid.UUID `json:"id"`
	ClassID   uuid.UUID `json:"class_id"`
	SubjectID uuid.UUID `json:"subject_id"`
	TeacherID uuid.UUID `json:"teacher_id"`
}

type Class struct {
	ClassID uuid.UUID `json:"class_id"`
	Name    string    `json:"name"`
}

type ClassPromotion struct {
	ClassID     uuid.UUID   `json:"class_id"`
	NextClassID pgtype.UUID `json:"next_class_id"`
}

type DisciplineRecord struct {
	DisciplineID uuid.UUID   `json:"discipline_id"`
	StudentID    uuid.UUID   `json:"student_id"`
	TermID       uuid.UUID   `json:"term_id"`
	Date         pgtype.Date `json:"date"`
	Description  string      `json:"description"`
	ActionTaken  pgtype.Text `json:"action_taken"`
	ReportedBy   pgtype.UUID `json:"reported_by"`
	Notes        pgtype.Text `json:"notes"`
}

type Fee struct {
	FeesID         uuid.UUID      `json:"fees_id"`
	FeeStructureID uuid.UUID      `json:"fee_structure_id"`
	StudentID      uuid.UUID      `json:"student_id"`
	Paid           pgtype.Numeric `json:"paid"`
	Arrears        pgtype.Numeric `json:"arrears"`
	Status         string         `json:"status"`
}

type FeeStructure struct {
	FeeStructureID uuid.UUID      `json:"fee_structure_id"`
	TermID         uuid.UUID      `json:"term_id"`
	ClassID        uuid.UUID      `json:"class_id"`
	Required       pgtype.Numeric `json:"required"`
}

type Grade struct {
	GradeID   uuid.UUID      `json:"grade_id"`
	StudentID uuid.UUID      `json:"student_id"`
	SubjectID uuid.UUID      `json:"subject_id"`
	TermID    uuid.UUID      `json:"term_id"`
	Score     pgtype.Numeric `json:"score"`
	Remark    pgtype.Text    `json:"remark"`
}

type Guardian struct {
	GuardianID   uuid.UUID   `json:"guardian_id"`
	GuardianName string      `json:"guardian_name"`
	PhoneNumber1 pgtype.Text `json:"phone_number_1"`
	PhoneNumber2 pgtype.Text `json:"phone_number_2"`
	Gender       string      `json:"gender"`
	Profession   pgtype.Text `json:"profession"`
}

type NumberCounter struct {
	Type    string `json:"type"`
	Year    string `json:"year"`
	LastVal int32  `json:"last_val"`
}

type PromotionHistory struct {
	PromotionHistoryID uuid.UUID          `json:"promotion_history_id"`
	StoredTermID       uuid.UUID          `json:"stored_term_id"`
	PromotionDate      pgtype.Timestamptz `json:"promotion_date"`
	IsUndone           bool               `json:"is_undone"`
}

type Remark struct {
	RemarksID           uuid.UUID          `json:"remarks_id"`
	StudentID           uuid.UUID          `json:"student_id"`
	TermID              uuid.UUID          `json:"term_id"`
	ContentClassTeacher pgtype.Text        `json:"content_class_teacher"`
	ContentHeadTeacher  pgtype.Text        `json:"content_head_teacher"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	RoleID      uuid.UUID   `json:"role_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Session struct {
	ID        uuid.UUID          `json:"id"`
	SessionID uuid.UUID          `json:"session_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Expires   pgtype.Timestamptz `json:"expires"`
}

type Student struct {
	StudentID      uuid.UUID   `json:"student_id"`
	StudentNo      string      `json:"student_no"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
	LastName       string      `json:"last_name"`
	MiddleName     pgtype.Text `json:"middle_name"`
	FirstName      string      `json:"first_name"`
	Gender         string      `json:"gender"`
	DateOfBirth    pgtype.Date `json:"date_of_birth"`
	Status         string      `json:"status"`
	Promoted       bool        `json:"promoted"`
	Graduated      bool        `json:"graduated"`
	Suspended      bool        `json:"suspended"`
}

type StudentClass struct {
	StudentClassID  uuid.UUID   `json:"student_class_id"`
	StudentID       uuid.UUID   `json:"student_id"`
	PreviousClassID pgtype.UUID `json:"previous_class_id"`
	ClassID         uuid.UUID   `json:"class_id"`
	TermID          uuid.UUID   `json:"term_id"`
}

type StudentGradesView struct {
	StudentID  uuid.UUID     `json:"student_id"`
	StudentNo  string        `json:"student_no"`
	LastName   string        `json:"last_name"`
	FirstName  string        `json:"first_name"`
	MiddleName pgtype.Text   `json:"middle_name"`
	ClassID    uuid.UUID     `json:"class_id"`
	ClassName  string        `json:"class_name"`
	Grades     dto.GradesMap `json:"grades"`
}

type StudentGuardian struct {
	StudentID  uuid.UUID `json:"student_id"`
	GuardianID uuid.UUID `json:"guardian_id"`
}

type StudentPromotionHistoryDetail struct {
	StudentPromotionHistoryDetailID uuid.UUID   `json:"student_promotion_history_detail_id"`
	PromotionHistoryID              uuid.UUID   `json:"promotion_history_id"`
	StudentID                       uuid.UUID   `json:"student_id"`
	PreviousClassID                 pgtype.UUID `json:"previous_class_id"`
	ClassID                         uuid.UUID   `json:"class_id"`
	Promoted                        bool        `json:"promoted"`
	Status                          string      `json:"status"`
	Graduated                       bool        `json:"graduated"`
}

type Subject struct {
	SubjectID uuid.UUID `json:"subject_id"`
	ClassID   uuid.UUID `json:"class_id"`
	Name      string    `json:"name"`
}

type Term struct {
	TermID         uuid.UUID                 `json:"term_id"`
	AcademicYearID uuid.UUID                 `json:"academic_year_id"`
	PreviousTermID pgtype.UUID               `json:"previous_term_id"`
	Name           string                    `json:"name"`
	StartDate      pgtype.Date               `json:"start_date"`
	EndDate        pgtype.Date               `json:"end_date"`
	Active         bool                      `json:"active"`
	Period         pgtype.Range[pgtype.Date] `json:"period"`
}

type User struct {
	UserID      uuid.UUID          `json:"user_id"`
	UserNo      string             `json:"user_no"`
	LastName    string             `json:"last_name"`
	FirstName   string             `json:"first_name"`
	Gender      string             `json:"gender"`
	Email       pgtype.Text        `json:"email"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Password    string             `json:"password"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	RoleID      uuid.UUID          `json:"role_id"`
}

type VirtualClassroom struct {
	StudentID      uuid.UUID   `json:"student_id"`
	StudentNo      string      `json:"student_no"`
	StudentName    interface{} `json:"student_name"`
	SubjectID      uuid.UUID   `json:"subject_id"`
	SubjectName    string      `json:"subject_name"`
	ClassID        uuid.UUID   `json:"class_id"`
	ClassName      string      `json:"class_name"`
	TeacherID      uuid.UUID   `json:"teacher_id"`
	TeacherName    interface{} `json:"teacher_name"`
	TermID         uuid.UUID   `json:"term_id"`
	TermName       string      `json:"term_name"`
	AcademicYearID uuid.UUID   `json:"academic_year_id"`
}
