// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(last_name, first_name, phone_number, email, gender, password) 
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING user_id, last_name, first_name, gender, email, phone_number, password, created_at, updated_at, role
`

type CreateUserParams struct {
	LastName    string
	FirstName   string
	PhoneNumber pgtype.Text
	Email       pgtype.Text
	Gender      string
	Password    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.LastName,
		arg.FirstName,
		arg.PhoneNumber,
		arg.Email,
		arg.Gender,
		arg.Password,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.LastName,
		&i.FirstName,
		&i.Gender,
		&i.Email,
		&i.PhoneNumber,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}
