// This file is auto-generated by @hey-api/openapi-ts

export const $AssignmentCreate = {
    properties: {
        teacher_id: {
            type: 'string',
            format: 'uuid',
            title: 'Teacher Id'
        },
        subject_id: {
            type: 'string',
            format: 'uuid',
            title: 'Subject Id'
        },
        class_form_id: {
            type: 'string',
            format: 'uuid',
            title: 'Class Form Id'
        }
    },
    type: 'object',
    required: ['teacher_id', 'subject_id', 'class_form_id'],
    title: 'AssignmentCreate'
} as const;

export const $AssignmentPublic = {
    properties: {
        teacher_id: {
            type: 'string',
            format: 'uuid',
            title: 'Teacher Id'
        },
        subject_id: {
            type: 'string',
            format: 'uuid',
            title: 'Subject Id'
        },
        class_form_id: {
            type: 'string',
            format: 'uuid',
            title: 'Class Form Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['teacher_id', 'subject_id', 'class_form_id', 'id'],
    title: 'AssignmentPublic'
} as const;

export const $AssignmentUpdate = {
    properties: {
        teacher_id: {
            type: 'string',
            format: 'uuid',
            title: 'Teacher Id'
        },
        subject_id: {
            type: 'string',
            format: 'uuid',
            title: 'Subject Id'
        },
        class_form_id: {
            type: 'string',
            format: 'uuid',
            title: 'Class Form Id'
        }
    },
    type: 'object',
    title: 'AssignmentUpdate'
} as const;

export const $AssignmentsPublic = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AssignmentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AssignmentsPublic'
} as const;

export const $Body_login_login_access_token = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const $ClassFormCreate = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ClassFormCreate'
} as const;

export const $ClassFormPublic = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'ClassFormPublic'
} as const;

export const $ClassFormUpdate = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        }
    },
    type: 'object',
    title: 'ClassFormUpdate'
} as const;

export const $ClassFormsPublic = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ClassFormPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ClassFormsPublic'
} as const;

export const $GradeCreate = {
    properties: {
        student_id: {
            type: 'string',
            format: 'uuid',
            title: 'Student Id'
        },
        subject_id: {
            type: 'string',
            format: 'uuid',
            title: 'Subject Id'
        },
        score: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Score'
        }
    },
    type: 'object',
    required: ['student_id', 'subject_id', 'score'],
    title: 'GradeCreate'
} as const;

export const $GradePublic = {
    properties: {
        student_id: {
            type: 'string',
            format: 'uuid',
            title: 'Student Id'
        },
        subject_id: {
            type: 'string',
            format: 'uuid',
            title: 'Subject Id'
        },
        score: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Score'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['student_id', 'subject_id', 'score', 'id'],
    title: 'GradePublic'
} as const;

export const $GradeUpdate = {
    properties: {
        student_id: {
            type: 'string',
            format: 'uuid',
            title: 'Student Id'
        },
        subject_id: {
            type: 'string',
            format: 'uuid',
            title: 'Subject Id'
        },
        score: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Score'
        }
    },
    type: 'object',
    required: ['student_id', 'subject_id'],
    title: 'GradeUpdate'
} as const;

export const $GradesPublic = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GradePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GradesPublic'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $Message = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const $NewPassword = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const $StudentCreate = {
    properties: {
        first_name: {
            type: 'string',
            maxLength: 255,
            minLength: 2,
            title: 'First Name'
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name'
        },
        last_name: {
            type: 'string',
            maxLength: 255,
            minLength: 2,
            title: 'Last Name'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        form_id: {
            type: 'string',
            format: 'uuid',
            title: 'Form Id'
        }
    },
    type: 'object',
    required: ['first_name', 'middle_name', 'last_name', 'contact', 'form_id'],
    title: 'StudentCreate'
} as const;

export const $StudentPublic = {
    properties: {
        first_name: {
            type: 'string',
            maxLength: 255,
            minLength: 2,
            title: 'First Name'
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name'
        },
        last_name: {
            type: 'string',
            maxLength: 255,
            minLength: 2,
            title: 'Last Name'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        form_id: {
            type: 'string',
            format: 'uuid',
            title: 'Form Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['first_name', 'middle_name', 'last_name', 'contact', 'form_id', 'id', 'owner_id'],
    title: 'StudentPublic'
} as const;

export const $StudentUpdate = {
    properties: {
        first_name: {
            type: 'string',
            maxLength: 255,
            minLength: 2,
            title: 'First Name'
        },
        middle_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Middle Name'
        },
        last_name: {
            type: 'string',
            maxLength: 255,
            minLength: 2,
            title: 'Last Name'
        },
        contact: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact'
        },
        form_id: {
            type: 'string',
            format: 'uuid',
            title: 'Form Id'
        }
    },
    type: 'object',
    required: ['middle_name', 'contact'],
    title: 'StudentUpdate'
} as const;

export const $StudentsPublic = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StudentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'StudentsPublic'
} as const;

export const $SubjectCreate = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'SubjectCreate'
} as const;

export const $SubjectPublic = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'SubjectPublic'
} as const;

export const $SubjectUpdate = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        }
    },
    type: 'object',
    title: 'SubjectUpdate'
} as const;

export const $SubjectsPublic = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SubjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SubjectsPublic'
} as const;

export const $Token = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const $UpdatePassword = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const $UserCreate = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_class_teacher: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Class Teacher',
            default: false
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const $UserPublic = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_class_teacher: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Class Teacher',
            default: false
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const $UserRegister = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const $UserUpdate = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_class_teacher: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Class Teacher',
            default: false
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const $UserUpdateMe = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const $UsersPublic = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;