// This file is auto-generated by @hey-api/openapi-ts

export const $Body_login_login_access_token = {
  properties: {
    grant_type: {
      anyOf: [
        {
          type: 'string',
          pattern: 'password'
        },
        {
          type: 'null'
        }
      ],
      title: 'Grant Type'
    },
    username: {
      type: 'string',
      title: 'Username'
    },
    password: {
      type: 'string',
      title: 'Password'
    },
    scope: {
      type: 'string',
      title: 'Scope',
      default: ''
    },
    client_id: {
      anyOf: [
        {
          type: 'string'
        },
        {
          type: 'null'
        }
      ],
      title: 'Client Id'
    },
    client_secret: {
      anyOf: [
        {
          type: 'string'
        },
        {
          type: 'null'
        }
      ],
      title: 'Client Secret'
    }
  },
  type: 'object',
  required: ['username', 'password'],
  title: 'Body_login-login_access_token'
} as const;

export const $HTTPValidationError = {
  properties: {
    detail: {
      items: {
        '$ref': '#/components/schemas/ValidationError'
      },
      type: 'array',
      title: 'Detail'
    }
  },
  type: 'object',
  title: 'HTTPValidationError'
} as const;

export const $Message = {
  properties: {
    message: {
      type: 'string',
      title: 'Message'
    }
  },
  type: 'object',
  required: ['message'],
  title: 'Message'
} as const;

export const $NewPassword = {
  properties: {
    token: {
      type: 'string',
      title: 'Token'
    },
    new_password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'New Password'
    }
  },
  type: 'object',
  required: ['token', 'new_password'],
  title: 'NewPassword'
} as const;

export const $StudentCreate = {
  properties: {
    first_name: {
      type: 'string',
      maxLength: 255,
      minLength: 2,
      title: 'First Name'
    },
    last_name: {
      type: 'string',
      maxLength: 255,
      minLength: 2,
      title: 'Last Name'
    },
    form: {
      type: 'integer',
      maxLength: 255,
      minLength: 1,
      title: 'Form'
    }
  },
  type: 'object',
  required: ['first_name', 'last_name', 'form'],
  title: 'StudentCreate'
} as const;

export const $StudentPublic = {
  properties: {
    first_name: {
      type: 'string',
      maxLength: 255,
      minLength: 2,
      title: 'First Name'
    },
    last_name: {
      type: 'string',
      maxLength: 255,
      minLength: 2,
      title: 'Last Name'
    },
    form: {
      type: 'integer',
      maxLength: 255,
      minLength: 1,
      title: 'Form'
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id'
    },
    owner_id: {
      type: 'string',
      format: 'uuid',
      title: 'Owner Id'
    }
  },
  type: 'object',
  required: ['first_name', 'last_name', 'form', 'id', 'owner_id'],
  title: 'StudentPublic'
} as const;

export const $StudentUpdate = {
  properties: {
    first_name: {
      type: 'string',
      maxLength: 255,
      minLength: 2,
      title: 'First Name'
    },
    last_name: {
      type: 'string',
      maxLength: 255,
      minLength: 2,
      title: 'Last Name'
    },
    form: {
      type: 'integer',
      maxLength: 255,
      minLength: 1,
      title: 'Form'
    }
  },
  type: 'object',
  required: ['first_name', 'last_name', 'form'],
  title: 'StudentUpdate'
} as const;

export const $StudentsPublic = {
  properties: {
    data: {
      items: {
        '$ref': '#/components/schemas/StudentPublic'
      },
      type: 'array',
      title: 'Data'
    },
    count: {
      type: 'integer',
      title: 'Count'
    }
  },
  type: 'object',
  required: ['data', 'count'],
  title: 'StudentsPublic'
} as const;

export const $Token = {
  properties: {
    access_token: {
      type: 'string',
      title: 'Access Token'
    },
    token_type: {
      type: 'string',
      title: 'Token Type',
      default: 'bearer'
    }
  },
  type: 'object',
  required: ['access_token'],
  title: 'Token'
} as const;

export const $UpdatePassword = {
  properties: {
    current_password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'Current Password'
    },
    new_password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'New Password'
    }
  },
  type: 'object',
  required: ['current_password', 'new_password'],
  title: 'UpdatePassword'
} as const;

export const $UserCreate = {
  properties: {
    email: {
      type: 'string',
      maxLength: 255,
      format: 'email',
      title: 'Email'
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      default: true
    },
    is_superuser: {
      type: 'boolean',
      title: 'Is Superuser',
      default: false
    },
    full_name: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255
        },
        {
          type: 'null'
        }
      ],
      title: 'Full Name'
    },
    password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'Password'
    }
  },
  type: 'object',
  required: ['email', 'password'],
  title: 'UserCreate'
} as const;

export const $UserPublic = {
  properties: {
    email: {
      type: 'string',
      maxLength: 255,
      format: 'email',
      title: 'Email'
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      default: true
    },
    is_superuser: {
      type: 'boolean',
      title: 'Is Superuser',
      default: false
    },
    full_name: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255
        },
        {
          type: 'null'
        }
      ],
      title: 'Full Name'
    },
    id: {
      type: 'string',
      format: 'uuid',
      title: 'Id'
    }
  },
  type: 'object',
  required: ['email', 'id'],
  title: 'UserPublic'
} as const;

export const $UserRegister = {
  properties: {
    email: {
      type: 'string',
      maxLength: 255,
      format: 'email',
      title: 'Email'
    },
    password: {
      type: 'string',
      maxLength: 40,
      minLength: 8,
      title: 'Password'
    },
    full_name: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255
        },
        {
          type: 'null'
        }
      ],
      title: 'Full Name'
    }
  },
  type: 'object',
  required: ['email', 'password'],
  title: 'UserRegister'
} as const;

export const $UserUpdate = {
  properties: {
    email: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255,
          format: 'email'
        },
        {
          type: 'null'
        }
      ],
      title: 'Email'
    },
    is_active: {
      type: 'boolean',
      title: 'Is Active',
      default: true
    },
    is_superuser: {
      type: 'boolean',
      title: 'Is Superuser',
      default: false
    },
    full_name: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255
        },
        {
          type: 'null'
        }
      ],
      title: 'Full Name'
    },
    password: {
      anyOf: [
        {
          type: 'string',
          maxLength: 40,
          minLength: 8
        },
        {
          type: 'null'
        }
      ],
      title: 'Password'
    }
  },
  type: 'object',
  title: 'UserUpdate'
} as const;

export const $UserUpdateMe = {
  properties: {
    full_name: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255
        },
        {
          type: 'null'
        }
      ],
      title: 'Full Name'
    },
    email: {
      anyOf: [
        {
          type: 'string',
          maxLength: 255,
          format: 'email'
        },
        {
          type: 'null'
        }
      ],
      title: 'Email'
    }
  },
  type: 'object',
  title: 'UserUpdateMe'
} as const;

export const $UsersPublic = {
  properties: {
    data: {
      items: {
        '$ref': '#/components/schemas/UserPublic'
      },
      type: 'array',
      title: 'Data'
    },
    count: {
      type: 'integer',
      title: 'Count'
    }
  },
  type: 'object',
  required: ['data', 'count'],
  title: 'UsersPublic'
} as const;

export const $ValidationError = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: 'string'
          },
          {
            type: 'integer'
          }
        ]
      },
      type: 'array',
      title: 'Location'
    },
    msg: {
      type: 'string',
      title: 'Message'
    },
    type: {
      type: 'string',
      title: 'Error Type'
    }
  },
  type: 'object',
  required: ['loc', 'msg', 'type'],
  title: 'ValidationError'
} as const;
