// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginAccessTokenData, LoginAccessTokenResponse, TestTokenResponse, RecoverPasswordData, RecoverPasswordResponse, ResetPasswordData, ResetPasswordResponse, RecoverPasswordHtmlContentData, RecoverPasswordHtmlContentResponse, ReadUsersData, ReadUsersResponse, CreateUserData, CreateUserResponse, ReadUserMeResponse, DeleteUserMeResponse, UpdateUserMeData, UpdateUserMeResponse, UpdatePasswordMeData, UpdatePasswordMeResponse, RegisterUserData, RegisterUserResponse, ReadUserByIdData, ReadUserByIdResponse, UpdateUserData, UpdateUserResponse, DeleteUserData, DeleteUserResponse, TestEmailData, TestEmailResponse, ReadStudentsData, ReadStudentsResponse, CreateStudentData, CreateStudentResponse, ReadStudentData, ReadStudentResponse, UpdateStudentData, UpdateStudentResponse, DeleteStudentData, DeleteStudentResponse, ReadGradesData, ReadGradesResponse, CreateGradeData, CreateGradeResponse, ReadGradeData, ReadGradeResponse, UpdateGradeData, UpdateGradeResponse, DeleteGradeData, DeleteGradeResponse, ReadSubjectsData, ReadSubjectsResponse, CreateSubjectData, CreateSubjectResponse, ReadSubjectData, ReadSubjectResponse, UpdateSubjectData, UpdateSubjectResponse, DeleteSubjectData, DeleteSubjectResponse, ReadClassFormsData, ReadClassFormsResponse, CreateClassFormData, CreateClassFormResponse, ReadClassFormData, ReadClassFormResponse, UpdateClassFormData, UpdateClassFormResponse, DeleteClassFormData, DeleteClassFormResponse, ReadAssignmentsData, ReadAssignmentsResponse, CreateAssignmentData, CreateAssignmentResponse, ReadAssignmentData, ReadAssignmentResponse, UpdateAssignmentData, UpdateAssignmentResponse, DeleteAssignmentData, DeleteAssignmentResponse } from './types.gen';

/**
 * Login Access Token
 * OAuth2 compatible token login, get an access token for future requests
 * @param data The data for the request.
 * @param data.formData
 * @returns Token Successful Response
 * @throws ApiError
 */
export const loginAccessToken = (data: LoginAccessTokenData): CancelablePromise<LoginAccessTokenResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/login/access-token',
    formData: data.formData,
    mediaType: 'application/x-www-form-urlencoded',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Test Token
 * Test access token
 * @returns UserPublic Successful Response
 * @throws ApiError
 */
export const testToken = (): CancelablePromise<TestTokenResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/login/test-token'
}); };

/**
 * Recover Password
 * Password Recovery
 * @param data The data for the request.
 * @param data.email
 * @returns Message Successful Response
 * @throws ApiError
 */
export const recoverPassword = (data: RecoverPasswordData): CancelablePromise<RecoverPasswordResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/password-recovery/{email}',
    path: {
        email: data.email
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Reset Password
 * Reset password
 * @param data The data for the request.
 * @param data.requestBody
 * @returns Message Successful Response
 * @throws ApiError
 */
export const resetPassword = (data: ResetPasswordData): CancelablePromise<ResetPasswordResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/reset-password/',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Recover Password Html Content
 * HTML Content for Password Recovery
 * @param data The data for the request.
 * @param data.email
 * @returns string Successful Response
 * @throws ApiError
 */
export const recoverPasswordHtmlContent = (data: RecoverPasswordHtmlContentData): CancelablePromise<RecoverPasswordHtmlContentResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/password-recovery-html-content/{email}',
    path: {
        email: data.email
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Users
 * Retrieve users.
 * @param data The data for the request.
 * @param data.skip
 * @param data.limit
 * @returns UsersPublic Successful Response
 * @throws ApiError
 */
export const readUsers = (data: ReadUsersData = {}): CancelablePromise<ReadUsersResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/users/',
    query: {
        skip: data.skip,
        limit: data.limit
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Create User
 * Create new user.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns UserPublic Successful Response
 * @throws ApiError
 */
export const createUser = (data: CreateUserData): CancelablePromise<CreateUserResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/users/',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read User Me
 * Get current user.
 * @returns UserPublic Successful Response
 * @throws ApiError
 */
export const readUserMe = (): CancelablePromise<ReadUserMeResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/users/me'
}); };

/**
 * Delete User Me
 * Delete own user.
 * @returns Message Successful Response
 * @throws ApiError
 */
export const deleteUserMe = (): CancelablePromise<DeleteUserMeResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/users/me'
}); };

/**
 * Update User Me
 * Update own user.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns UserPublic Successful Response
 * @throws ApiError
 */
export const updateUserMe = (data: UpdateUserMeData): CancelablePromise<UpdateUserMeResponse> => { return __request(OpenAPI, {
    method: 'PATCH',
    url: '/api/users/me',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Update Password Me
 * Update own password.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns Message Successful Response
 * @throws ApiError
 */
export const updatePasswordMe = (data: UpdatePasswordMeData): CancelablePromise<UpdatePasswordMeResponse> => { return __request(OpenAPI, {
    method: 'PATCH',
    url: '/api/users/me/password',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Register User
 * Create new user without the need to be logged in.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns UserPublic Successful Response
 * @throws ApiError
 */
export const registerUser = (data: RegisterUserData): CancelablePromise<RegisterUserResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/users/signup',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read User By Id
 * Get a specific user by id.
 * @param data The data for the request.
 * @param data.userId
 * @returns UserPublic Successful Response
 * @throws ApiError
 */
export const readUserById = (data: ReadUserByIdData): CancelablePromise<ReadUserByIdResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/users/{user_id}',
    path: {
        user_id: data.userId
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Update User
 * Update a user.
 * @param data The data for the request.
 * @param data.userId
 * @param data.requestBody
 * @returns UserPublic Successful Response
 * @throws ApiError
 */
export const updateUser = (data: UpdateUserData): CancelablePromise<UpdateUserResponse> => { return __request(OpenAPI, {
    method: 'PATCH',
    url: '/api/users/{user_id}',
    path: {
        user_id: data.userId
    },
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Delete User
 * Delete a user.
 * @param data The data for the request.
 * @param data.userId
 * @returns Message Successful Response
 * @throws ApiError
 */
export const deleteUser = (data: DeleteUserData): CancelablePromise<DeleteUserResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/users/{user_id}',
    path: {
        user_id: data.userId
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Test Email
 * Test emails.
 * @param data The data for the request.
 * @param data.emailTo
 * @returns Message Successful Response
 * @throws ApiError
 */
export const testEmail = (data: TestEmailData): CancelablePromise<TestEmailResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/utils/test-email/',
    query: {
        email_to: data.emailTo
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Students
 * Retrieve students.
 * @param data The data for the request.
 * @param data.skip
 * @param data.limit
 * @returns StudentsPublic Successful Response
 * @throws ApiError
 */
export const readStudents = (data: ReadStudentsData = {}): CancelablePromise<ReadStudentsResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/students/',
    query: {
        skip: data.skip,
        limit: data.limit
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Create Student
 * Create new student.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns StudentPublic Successful Response
 * @throws ApiError
 */
export const createStudent = (data: CreateStudentData): CancelablePromise<CreateStudentResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/students/',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Student
 * Get student by ID.
 * @param data The data for the request.
 * @param data.id
 * @returns StudentPublic Successful Response
 * @throws ApiError
 */
export const readStudent = (data: ReadStudentData): CancelablePromise<ReadStudentResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/students/{id}',
    path: {
        id: data.id
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Update Student
 * Update a student.
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns StudentPublic Successful Response
 * @throws ApiError
 */
export const updateStudent = (data: UpdateStudentData): CancelablePromise<UpdateStudentResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/students/{id}',
    path: {
        id: data.id
    },
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Delete Student
 * Delete a student.
 * @param data The data for the request.
 * @param data.id
 * @returns Message Successful Response
 * @throws ApiError
 */
export const deleteStudent = (data: DeleteStudentData): CancelablePromise<DeleteStudentResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/students/{id}',
    path: {
        id: data.id
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Grades
 * Retrieve grades.
 * @param data The data for the request.
 * @param data.skip
 * @param data.limit
 * @returns GradesPublic Successful Response
 * @throws ApiError
 */
export const readGrades = (data: ReadGradesData = {}): CancelablePromise<ReadGradesResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/grades/',
    query: {
        skip: data.skip,
        limit: data.limit
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Create Grade
 * Create new grade. Prevent duplicate grades for the same student and subject.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns GradePublic Successful Response
 * @throws ApiError
 */
export const createGrade = (data: CreateGradeData): CancelablePromise<CreateGradeResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/grades/',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Grade
 * Get grade by ID.
 * @param data The data for the request.
 * @param data.id
 * @returns GradePublic Successful Response
 * @throws ApiError
 */
export const readGrade = (data: ReadGradeData): CancelablePromise<ReadGradeResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/grades/{id}',
    path: {
        id: data.id
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Update Grade
 * Update a grade.
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns GradePublic Successful Response
 * @throws ApiError
 */
export const updateGrade = (data: UpdateGradeData): CancelablePromise<UpdateGradeResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/grades/{id}',
    path: {
        id: data.id
    },
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Delete Grade
 * Delete a grade.
 * @param data The data for the request.
 * @param data.id
 * @returns Message Successful Response
 * @throws ApiError
 */
export const deleteGrade = (data: DeleteGradeData): CancelablePromise<DeleteGradeResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/grades/{id}',
    path: {
        id: data.id
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Subjects
 * Retrieve subjects.
 * @param data The data for the request.
 * @param data.skip
 * @param data.limit
 * @returns SubjectsPublic Successful Response
 * @throws ApiError
 */
export const readSubjects = (data: ReadSubjectsData = {}): CancelablePromise<ReadSubjectsResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/subjects/',
    query: {
        skip: data.skip,
        limit: data.limit
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Create Subject
 * Create new subject.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns SubjectPublic Successful Response
 * @throws ApiError
 */
export const createSubject = (data: CreateSubjectData): CancelablePromise<CreateSubjectResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/subjects/',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Subject
 * Get subject by ID.
 * @param data The data for the request.
 * @param data.id
 * @returns SubjectPublic Successful Response
 * @throws ApiError
 */
export const readSubject = (data: ReadSubjectData): CancelablePromise<ReadSubjectResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/subjects/{id}',
    path: {
        id: data.id
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Update Subject
 * Update a subject.
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns SubjectPublic Successful Response
 * @throws ApiError
 */
export const updateSubject = (data: UpdateSubjectData): CancelablePromise<UpdateSubjectResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/subjects/{id}',
    path: {
        id: data.id
    },
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Delete Subject
 * Delete a subject.
 * @param data The data for the request.
 * @param data.id
 * @returns Message Successful Response
 * @throws ApiError
 */
export const deleteSubject = (data: DeleteSubjectData): CancelablePromise<DeleteSubjectResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/subjects/{id}',
    path: {
        id: data.id
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Class Forms
 * Retrieve class forms (forms 1, 2, 3, 4).
 * @param data The data for the request.
 * @param data.skip
 * @param data.limit
 * @returns ClassFormsPublic Successful Response
 * @throws ApiError
 */
export const readClassForms = (data: ReadClassFormsData = {}): CancelablePromise<ReadClassFormsResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/class-forms/',
    query: {
        skip: data.skip,
        limit: data.limit
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Create Class Form
 * Create new class form.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns ClassFormPublic Successful Response
 * @throws ApiError
 */
export const createClassForm = (data: CreateClassFormData): CancelablePromise<CreateClassFormResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/class-forms/',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Class Form
 * Get class form by ID.
 * @param data The data for the request.
 * @param data.id
 * @returns ClassFormPublic Successful Response
 * @throws ApiError
 */
export const readClassForm = (data: ReadClassFormData): CancelablePromise<ReadClassFormResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/class-forms/{id}',
    path: {
        id: data.id
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Update Class Form
 * Update a class form.
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns ClassFormPublic Successful Response
 * @throws ApiError
 */
export const updateClassForm = (data: UpdateClassFormData): CancelablePromise<UpdateClassFormResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/class-forms/{id}',
    path: {
        id: data.id
    },
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Delete Class Form
 * Delete a class form.
 * @param data The data for the request.
 * @param data.id
 * @returns Message Successful Response
 * @throws ApiError
 */
export const deleteClassForm = (data: DeleteClassFormData): CancelablePromise<DeleteClassFormResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/class-forms/{id}',
    path: {
        id: data.id
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Assignments
 * Retrieve assignments.
 * @param data The data for the request.
 * @param data.skip
 * @param data.limit
 * @returns AssignmentsPublic Successful Response
 * @throws ApiError
 */
export const readAssignments = (data: ReadAssignmentsData = {}): CancelablePromise<ReadAssignmentsResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/assignments/',
    query: {
        skip: data.skip,
        limit: data.limit
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Create Assignment
 * Create new assignment.
 * Check for duplicate (same teacher, subject, and class form) before creation.
 * @param data The data for the request.
 * @param data.requestBody
 * @returns AssignmentPublic Successful Response
 * @throws ApiError
 */
export const createAssignment = (data: CreateAssignmentData): CancelablePromise<CreateAssignmentResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/api/assignments/',
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Read Assignment
 * Get assignment by ID.
 * @param data The data for the request.
 * @param data.id
 * @returns AssignmentPublic Successful Response
 * @throws ApiError
 */
export const readAssignment = (data: ReadAssignmentData): CancelablePromise<ReadAssignmentResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/api/assignments/{id}',
    path: {
        id: data.id
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Update Assignment
 * Update an assignment.
 * @param data The data for the request.
 * @param data.id
 * @param data.requestBody
 * @returns AssignmentPublic Successful Response
 * @throws ApiError
 */
export const updateAssignment = (data: UpdateAssignmentData): CancelablePromise<UpdateAssignmentResponse> => { return __request(OpenAPI, {
    method: 'PUT',
    url: '/api/assignments/{id}',
    path: {
        id: data.id
    },
    body: data.requestBody,
    mediaType: 'application/json',
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Delete Assignment
 * Delete an assignment.
 * @param data The data for the request.
 * @param data.id
 * @returns Message Successful Response
 * @throws ApiError
 */
export const deleteAssignment = (data: DeleteAssignmentData): CancelablePromise<DeleteAssignmentResponse> => { return __request(OpenAPI, {
    method: 'DELETE',
    url: '/api/assignments/{id}',
    path: {
        id: data.id
    },
    errors: {
        422: 'Validation Error'
    }
}); };