// This file is auto-generated by @hey-api/openapi-ts

export type AssignmentCreate = {
    teacher_id: string;
    subject_id: string;
    class_form_id: string;
};

export type AssignmentPublic = {
    teacher_id: string;
    subject_id: string;
    class_form_id: string;
    id: string;
};

export type AssignmentUpdate = {
    teacher_id?: string;
    subject_id?: string;
    class_form_id?: string;
};

export type AssignmentsPublic = {
    data: Array<AssignmentPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ClassFormCreate = {
    name: string;
};

export type ClassFormPublic = {
    name: string;
    id: string;
};

export type ClassFormUpdate = {
    name?: string;
};

export type ClassFormsPublic = {
    data: Array<ClassFormPublic>;
    count: number;
};

export type GradeCreate = {
    student_id: string;
    subject_id: string;
    score: number;
};

export type GradePublic = {
    student_id: string;
    subject_id: string;
    score: number;
    id: string;
};

export type GradeUpdate = {
    student_id: string;
    subject_id: string;
    score?: number;
};

export type GradesPublic = {
    data: Array<GradePublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type StudentCreate = {
    first_name: string;
    last_name: string;
    form_id: string;
};

export type StudentPublic = {
    first_name: string;
    last_name: string;
    form_id: string;
    id: string;
    owner_id: string;
};

export type StudentUpdate = {
    first_name?: string;
    last_name?: string;
    form_id?: string;
};

export type StudentsPublic = {
    data: Array<StudentPublic>;
    count: number;
};

export type SubjectCreate = {
    name: string;
};

export type SubjectPublic = {
    name: string;
    id: string;
};

export type SubjectUpdate = {
    name?: string;
};

export type SubjectsPublic = {
    data: Array<SubjectPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserUpdate = {
    email?: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginAccessTokenResponse = (Token);

export type TestTokenResponse = (UserPublic);

export type RecoverPasswordData = {
    email: string;
};

export type RecoverPasswordResponse = (Message);

export type ResetPasswordData = {
    requestBody: NewPassword;
};

export type ResetPasswordResponse = (Message);

export type RecoverPasswordHtmlContentData = {
    email: string;
};

export type RecoverPasswordHtmlContentResponse = (string);

export type ReadUsersData = {
    limit?: number;
    skip?: number;
};

export type ReadUsersResponse = (UsersPublic);

export type CreateUserData = {
    requestBody: UserCreate;
};

export type CreateUserResponse = (UserPublic);

export type ReadUserMeResponse = (UserPublic);

export type DeleteUserMeResponse = (Message);

export type UpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UpdateUserMeResponse = (UserPublic);

export type UpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UpdatePasswordMeResponse = (Message);

export type RegisterUserData = {
    requestBody: UserRegister;
};

export type RegisterUserResponse = (UserPublic);

export type ReadUserByIdData = {
    userId: string;
};

export type ReadUserByIdResponse = (UserPublic);

export type UpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UpdateUserResponse = (UserPublic);

export type DeleteUserData = {
    userId: string;
};

export type DeleteUserResponse = (Message);

export type TestEmailData = {
    emailTo: string;
};

export type TestEmailResponse = (Message);

export type ReadStudentsData = {
    limit?: number;
    skip?: number;
};

export type ReadStudentsResponse = (StudentsPublic);

export type CreateStudentData = {
    requestBody: StudentCreate;
};

export type CreateStudentResponse = (StudentPublic);

export type ReadStudentData = {
    id: string;
};

export type ReadStudentResponse = (StudentPublic);

export type UpdateStudentData = {
    id: string;
    requestBody: StudentUpdate;
};

export type UpdateStudentResponse = (StudentPublic);

export type DeleteStudentData = {
    id: string;
};

export type DeleteStudentResponse = (Message);

export type ReadGradesData = {
    limit?: number;
    skip?: number;
};

export type ReadGradesResponse = (GradesPublic);

export type CreateGradeData = {
    requestBody: GradeCreate;
};

export type CreateGradeResponse = (GradePublic);

export type ReadGradeData = {
    id: string;
};

export type ReadGradeResponse = (GradePublic);

export type UpdateGradeData = {
    id: string;
    requestBody: GradeUpdate;
};

export type UpdateGradeResponse = (GradePublic);

export type DeleteGradeData = {
    id: string;
};

export type DeleteGradeResponse = (Message);

export type ReadSubjectsData = {
    limit?: number;
    skip?: number;
};

export type ReadSubjectsResponse = (SubjectsPublic);

export type CreateSubjectData = {
    requestBody: SubjectCreate;
};

export type CreateSubjectResponse = (SubjectPublic);

export type ReadSubjectData = {
    id: string;
};

export type ReadSubjectResponse = (SubjectPublic);

export type UpdateSubjectData = {
    id: string;
    requestBody: SubjectUpdate;
};

export type UpdateSubjectResponse = (SubjectPublic);

export type DeleteSubjectData = {
    id: string;
};

export type DeleteSubjectResponse = (Message);

export type ReadClassFormsData = {
    limit?: number;
    skip?: number;
};

export type ReadClassFormsResponse = (ClassFormsPublic);

export type CreateClassFormData = {
    requestBody: ClassFormCreate;
};

export type CreateClassFormResponse = (ClassFormPublic);

export type ReadClassFormData = {
    id: string;
};

export type ReadClassFormResponse = (ClassFormPublic);

export type UpdateClassFormData = {
    id: string;
    requestBody: ClassFormUpdate;
};

export type UpdateClassFormResponse = (ClassFormPublic);

export type DeleteClassFormData = {
    id: string;
};

export type DeleteClassFormResponse = (Message);

export type ReadAssignmentsData = {
    limit?: number;
    skip?: number;
};

export type ReadAssignmentsResponse = (AssignmentsPublic);

export type CreateAssignmentData = {
    requestBody: AssignmentCreate;
};

export type CreateAssignmentResponse = (AssignmentPublic);

export type ReadAssignmentData = {
    id: string;
};

export type ReadAssignmentResponse = (AssignmentPublic);

export type UpdateAssignmentData = {
    id: string;
    requestBody: AssignmentUpdate;
};

export type UpdateAssignmentResponse = (AssignmentPublic);

export type DeleteAssignmentData = {
    id: string;
};

export type DeleteAssignmentResponse = (Message);