// This file is auto-generated by @hey-api/openapi-ts

export type AssignmentCreate = {
    teacher_id: string;
    subject_id: string;
    class_form_id: string;
};

export type AssignmentPublic = {
    teacher_id: string;
    subject_id: string;
    class_form_id: string;
    id: string;
};

export type AssignmentUpdate = {
    teacher_id?: string;
    subject_id?: string;
    class_form_id?: string;
};

export type AssignmentsPublic = {
    data: Array<AssignmentPublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ClassFormCreate = {
    name: string;
};

export type ClassFormPublic = {
    name: string;
    id: string;
};

export type ClassFormUpdate = {
    name?: string;
};

export type ClassFormsPublic = {
    data: Array<ClassFormPublic>;
    count: number;
};

export type GradeCreate = {
    student_id: string;
    subject_id: string;
    score: number;
};

export type GradePublic = {
    student_id: string;
    subject_id: string;
    score: number;
    id: string;
};

export type GradeUpdate = {
    student_id: string;
    subject_id: string;
    score?: number;
};

export type GradesPublic = {
    data: Array<GradePublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type StudentCreate = {
    first_name: string;
    middle_name: (string | null);
    last_name: string;
    contact: (string | null);
    form_id: string;
};

export type StudentPublic = {
    first_name: string;
    middle_name: (string | null);
    last_name: string;
    contact: (string | null);
    form_id: string;
    id: string;
    owner_id: string;
};

export type StudentUpdate = {
    first_name?: string;
    middle_name: (string | null);
    last_name?: string;
    contact: (string | null);
    form_id?: string;
};

export type StudentsPublic = {
    data: Array<StudentPublic>;
    count: number;
};

export type SubjectCreate = {
    name: string;
};

export type SubjectPublic = {
    name: string;
    id: string;
};

export type SubjectUpdate = {
    name?: string;
};

export type SubjectsPublic = {
    data: Array<SubjectPublic>;
    count: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserUpdate = {
    email?: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type StudentsReadStudentsData = {
    limit?: number;
    skip?: number;
};

export type StudentsReadStudentsResponse = (StudentsPublic);

export type StudentsCreateStudentData = {
    requestBody: StudentCreate;
};

export type StudentsCreateStudentResponse = (StudentPublic);

export type StudentsReadStudentData = {
    id: string;
};

export type StudentsReadStudentResponse = (StudentPublic);

export type StudentsUpdateStudentData = {
    id: string;
    requestBody: StudentUpdate;
};

export type StudentsUpdateStudentResponse = (StudentPublic);

export type StudentsDeleteStudentData = {
    id: string;
};

export type StudentsDeleteStudentResponse = (Message);

export type GradesReadGradesData = {
    limit?: number;
    skip?: number;
};

export type GradesReadGradesResponse = (GradesPublic);

export type GradesCreateGradeData = {
    requestBody: GradeCreate;
};

export type GradesCreateGradeResponse = (GradePublic);

export type GradesReadGradeData = {
    id: string;
};

export type GradesReadGradeResponse = (GradePublic);

export type GradesUpdateGradeData = {
    id: string;
    requestBody: GradeUpdate;
};

export type GradesUpdateGradeResponse = (GradePublic);

export type GradesDeleteGradeData = {
    id: string;
};

export type GradesDeleteGradeResponse = (Message);

export type SubjectsReadSubjectsData = {
    limit?: number;
    skip?: number;
};

export type SubjectsReadSubjectsResponse = (SubjectsPublic);

export type SubjectsCreateSubjectData = {
    requestBody: SubjectCreate;
};

export type SubjectsCreateSubjectResponse = (SubjectPublic);

export type SubjectsReadSubjectData = {
    id: string;
};

export type SubjectsReadSubjectResponse = (SubjectPublic);

export type SubjectsUpdateSubjectData = {
    id: string;
    requestBody: SubjectUpdate;
};

export type SubjectsUpdateSubjectResponse = (SubjectPublic);

export type SubjectsDeleteSubjectData = {
    id: string;
};

export type SubjectsDeleteSubjectResponse = (Message);

export type ClassFormsReadClassFormsData = {
    limit?: number;
    skip?: number;
};

export type ClassFormsReadClassFormsResponse = (ClassFormsPublic);

export type ClassFormsCreateClassFormData = {
    requestBody: ClassFormCreate;
};

export type ClassFormsCreateClassFormResponse = (ClassFormPublic);

export type ClassFormsReadClassFormData = {
    id: string;
};

export type ClassFormsReadClassFormResponse = (ClassFormPublic);

export type ClassFormsUpdateClassFormData = {
    id: string;
    requestBody: ClassFormUpdate;
};

export type ClassFormsUpdateClassFormResponse = (ClassFormPublic);

export type ClassFormsDeleteClassFormData = {
    id: string;
};

export type ClassFormsDeleteClassFormResponse = (Message);

export type AssignmentsReadAssignmentsData = {
    limit?: number;
    skip?: number;
};

export type AssignmentsReadAssignmentsResponse = (AssignmentsPublic);

export type AssignmentsCreateAssignmentData = {
    requestBody: AssignmentCreate;
};

export type AssignmentsCreateAssignmentResponse = (AssignmentPublic);

export type AssignmentsReadAssignmentData = {
    id: string;
};

export type AssignmentsReadAssignmentResponse = (AssignmentPublic);

export type AssignmentsUpdateAssignmentData = {
    id: string;
    requestBody: AssignmentUpdate;
};

export type AssignmentsUpdateAssignmentResponse = (AssignmentPublic);

export type AssignmentsDeleteAssignmentData = {
    id: string;
};

export type AssignmentsDeleteAssignmentResponse = (Message);