"""Make form_id not nullable in Student

Revision ID: 49f8ac345aed
Revises: 384916a3efe3
Create Date: 2024-08-31 13:01:55.111214

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '49f8ac345aed'
down_revision = '384916a3efe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
