"""add class teacher option

Revision ID: 5702657fbc50
Revises: fdc82a89fa8d
Create Date: 2024-09-02 03:03:59.948917

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5702657fbc50'
down_revision = 'fdc82a89fa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_class_teacher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_class_teacher')
    # ### end Alembic commands ###
