"""change_is_teacher

Revision ID: af5ebeef22e6
Revises: 5702657fbc50
Create Date: 2024-09-02 11:04:49.945380

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'af5ebeef22e6'
down_revision = '5702657fbc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_class_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_class_teacher',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
