"""Updated the student model

Revision ID: fdc82a89fa8d
Revises: 49f8ac345aed
Create Date: 2024-09-01 19:24:49.213300

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fdc82a89fa8d'
down_revision = '49f8ac345aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('middle_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('student', sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'contact')
    op.drop_column('student', 'middle_name')
    # ### end Alembic commands ###
