name: Deploy to Production

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: [self-hosted, production]
    env:
      ENV: ${{ secrets.ENV }}
      DOMAIN: ${{ secrets.DOMAIN }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      RANDOM_HEX: ${{ secrets.RANDOM_HEX }}
      SUPERUSER_ROLE: ${{ secrets.SUPERUSER_ROLE }}
      SUPERUSER_EMAIL: ${{ secrets.SUPERUSER_EMAIL }}
      SUPERUSER_PHONE: ${{ secrets.SUPERUSER_PHONE }}
      SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      GOOSE_DRIVER: ${{ secrets.GOOSE_DRIVER }}
      GOOSE_MIGRATION_DIR: ${{ secrets.GOOSE_MIGRATION_DIR }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      TAG: ${{ secrets.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "ENV=${{ secrets.ENV }}" > .env
          echo "DOMAIN=${{ secrets.DOMAIN }}" >> .env
          echo "PROJECT_NAME=${{ secrets.PROJECT_NAME }}" >> .env
          echo "RANDOM_HEX=${{ secrets.RANDOM_HEX }}" >> .env
          echo "SUPERUSER_ROLE=${{ secrets.SUPERUSER_ROLE }}" >> .env
          echo "SUPERUSER_EMAIL=${{ secrets.SUPERUSER_EMAIL }}" >> .env
          echo "SUPERUSER_PHONE=${{ secrets.SUPERUSER_PHONE }}" >> .env
          echo "SUPERUSER_PASSWORD=${{ secrets.SUPERUSER_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_SCHEMA=${{ secrets.DB_SCHEMA }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "GOOSE_DRIVER=${{ secrets.GOOSE_DRIVER }}" >> .env
          echo "GOOSE_MIGRATION_DIR=${{ secrets.GOOSE_MIGRATION_DIR }}" >> .env
          echo "DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}" >> .env
          echo "TAG=${{ secrets.TAG }}" >> .env

      - name: Build Docker Image
        run: docker compose -f docker-compose.yml build

      - name: Deploy Docker Compose
        run: docker compose -f docker-compose.yml up -d
