name: Deploy to Production

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on:
      - self-hosted
      - production
    env:
      ENV: ${{ secrets.ENV }}
      DOMAIN: ${{ secrets.DOMAIN }}
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
      RANDOM_HEX: ${{ secrets.RANDOM_HEX }}
      SUPERUSER_ROLE: ${{ secrets.SUPERUSER_ROLE }}
      SUPERUSER_EMAIL: ${{ secrets.SUPERUSER_EMAIL }}
      SUPERUSER_PHONE: ${{ secrets.SUPERUSER_PHONE }}
      SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
      GOOSE_DRIVER: ${{ secrets.GOOSE_DRIVER }}
      GOOSE_MIGRATION_DIR: ${{ secrets.GOOSE_MIGRATION_DIR }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      TAG: ${{ secrets.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: docker compose -f docker-compose.yml build
      - run: docker compose -f docker-compose.yml up -d
